import "./globals.css";

import { getServerSession } from "next-auth"
import Provider from "@/components/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
